<?php 
	$title = "Política de Privacidade";
	include("../_header.php");
?>
<div class="content">
	<div class="row">
		<div class="large-12">
			<!-- Main Slider -->
			<div id="slider">
				<figure style="width:100%; animation: 6s slidy1 infinite; -webkit-animation: 6s slidy1 infinite;">
					<img src="images/paginas/slide-empresa.png" style="width: 100%">
				</figure>
			</div>
			<!-- Main Content -->
			<article class="columns">
				<h2>Política de Privacidade</h2>
				<p>POR FAVOR, RECOMENDAMOS QUE A POLÍTICA DE PRIVACIDADE ABAIXO SEJA LIDA COM ATENÇÃO. ELA DESCREVE COMO SÃO TRATADAS AS INFORMAÇÕES PESSOAIS FORNECIDAS POR VOCÊ AO ACESSAR E UTILIZAR A Site ALLCRED PROMOTORA. AO UTILIZAR O SITE ALLCRED PROMOTORA, VOCÊ RECONHECE OS TERMOS E CONDIÇÕES DESTA POLÍTICA DE PRIVACIDADE E CONCORDA ESTAR VINCULADO ÀS SUAS CONDIÇÕES DE FORMA LIVRE E ESPONTANEA.</p>
                <p>Ao utilizar a o site AllCred Promotora (o “SITE”), de propriedade e titularidade da Mendes Promotora de Serviços de Cadastro LTDA EPP, inscrita no CNPJ/MF sob nº 08.768.992/0001-03, com sede na Rua Doutor Júlio Cardoso, 2007, Centro - Franca/SP e email: sac@allcredpromotora.com.br (a “AllCred Promotora”), Você concorda que a AllCred Promotora tenha acesso a certas informações pessoais suas.</p>
                <p>Esta Política de Privacidade esclarece quais informações pessoais podem ser acessadas e como elas serão utilizadas e armazenadas pela AllCred Promotora. A AllCred Promotora protege os direitos de privacidade dos usuários que se cadastrarem ou que de qualquer forma utilizarem o site, sejam eles Tomadores ou Investidores (“Usuários”), nos termos da lei aplicável, desta Política de Privacidade, dos Termos de Cadastro, dos Termos de Uso Tomador, dos Termos de Uso Investidor (em conjunto, os “Termos de Uso AllCred Promotora”) e da Política de Avaliação de Crédito.</p>
                <p>Todas as informações que possam identificá-lo individualmente, direta ou indiretamente, incluindo suas informações de cadastro, dados armazenados em cookies e informações a respeito do seu acesso e utilização do site (incluindo informações de Protocolo de Internet) não serão utilizadas para finalidades diversas das constantes nesta Política de Privacidade, da Política de Avaliação de Crédito e demais Termos de Uso AllCred Promotora.</p>
                <h3>1. SITE</h3>
                <p>O SITE é um sistema criado e desenvolvido para interação entre os Usuários. Para realizar seu cadastro na Site e assim desfrutar de todas as funcionalidades da Site você deverá fornecer determinadas informações, tais como:</p>
                <ol>
                    <li>seus dados pessoais necessários, tais como nome, endereço residencial, telefone de contato pessoal, e-mail, RG/RNE, CPF e outros dados necessários para a identificação pessoal.</li>
                    <li>dados corporativos e financeiros necessários para análise, elaboração e gerenciamento de Propostas para Captação de Recursos e Propostas de Crédito, de acordo com os Termos de Uso AllCred Promotora.</li>
                </ol>
                <h3>2. INFORMAÇÕES COLETADAS</h3>
                <p>A AllCred Promotora armazena seus dados pessoais, assim como dados de utilização, de relacionamento e perfil para criar estatísticas e gráficos, utilizados pela AllCred Promotora para aperfeiçoar e desenvolver uma melhor experiência para os Usuários no uso da Site.</p>
                <p>A AllCred Promotora coleta e armazena as seguintes informações: (i) as informações voluntariamente fornecidas quando da realização do seu cadastro junto à Site; (ii) informações financeiras advindas de uma ou mais instituições financeiras, do Brasil ou do exterior, incluindo, sem limitação, instituições financeiras (inclusive o Sistema de Informações de Crédito do Banco Central do Brasil), bureaus de crédito e quaisquer sistemas de pesquisa e análise, ou serviços e/ou repositórios de dados públicos ou privados aos quais a AllCred Promotora tenha acesso; (iii) informações decorrentes de sua utilização da Site, o que inclui o seu endereço IP, as seções da Site que Você acessou, tipo e linguagem do seu navegador; (iv) outros links de parceiros da Site (aplicações de internet), disponibilizados por intermédio desta; (v) o dia e hora de seu acesso e atividades realizadas junto à Site; (iv) qualquer conteúdo que Você tenha inserido na Site ou comunicação que estabeleça com outros Usuários através da Site; (v) qualquer aceitação sua aos termos que governam sua relação com a Site; e (vi) outras informações que permitam à AllCred Promotora melhorar a experiência dos Usuários na Site.</p>
                <p>As informações armazenadas pela AllCred Promotora poderão ser fornecidas a terceiros, tais como instituições financeiras e demais agentes de mercado designados, na medida em que forem necessárias para a análise, elaboração e gerenciamento de Propostas de Captação de Recursos, para fins de gerar uma Proposta de Crédito, em consonância com a Política de Avaliação de Crédito.</p>
                <p>Relatórios estatísticos sobre o acesso, utilização da Site e tendências de mercado, que não revelem a identidade dos Usuários, poderão também ser compartilhados com afiliados, subcontratados ou parceiros comerciais da AllCred Promotora.</p>
                <p>Inicialmente, as informações submetidas por Tomadores, de acordo com os Termos de Cadastro, serão utilizadas pela AllCred Promotora especificamente para fins de avaliação de crédito de Tomadores e manutenção de um banco de dados da AllCred Promotora. Essas informações não serão divulgadas a terceiros, exceto para parceiros da AllCred Promotora que colaborem com a referida avaliação de crédito do Tomador e apenas para o fim específico de permitir a necessária avaliação de crédito.</p>
                <p>Uma vez aceita uma Proposta de Crédito, de acordo com os Termos de Uso Tomador, as informações submetidas pelo Tomador ficarão disponíveis na Site, para análise de Investidores e demais agentes envolvidos nas operações da Site.</p>
                <p>Informações submetidas por Investidores, de acordo com os Termos de Uso Investidor, serão utilizadas exclusivamente pela AllCred Promotora e seus parceiros comerciais, para manutenção dos Serviços de Cobrança, gerenciamento de aplicações, recomendação de investimentos e manutenção de um banco de dados da AllCred Promotora.</p>
                <p>EM NENHUM CASO AS INFORMAÇÕES DOS USUÁRIOS SERÃO COMERCIALIZADAS JUNTO A TERCEIROS PELA ALLCRED PROMOTORA.</p>
                <h3>3. COMUNICAÇÕES</h3>
                <p>Quando qualquer Usuário se registra na Site, ele receberá e-mails para confirmar ações e solicitações específicas. Você receberá notificações referentes a etapas importantes do seu relacionamento com a AllCred Promotora. Essas notificações transacionais não possuem opções de desligamento (opt-out), uma vez que são enviadas por medidas de segurança pela Site. Poderemos também responder e-mails enviados por Usuários, se aplicável. Eventualmente enviaremos pesquisas e outras comunicações (diretamente ou por empresas parceiras) que julgarmos relevantes para Você, mas essas comunicações são de recebimento voluntário e Você poderá programar sua conta para não recebê-las (opt-out).</p>
                <h3>4. O QUE SÃO “COOKIES” E “BEACONS”?</h3>
                <p>Ao navegar na Site ou utilizar qualquer um de seus recursos ou ferramentas, um cookie será enviado para o seu computador. Um cookie é um fragmento de dado que o identifica como um usuário único, reconhecendo, acompanhando e armazenando as suas informações de navegação. Os cookies são utilizados para proporcionar a Você conteúdo personalizado, assim como para facilitar e agilizar o preenchimento de determinados campos. Você pode configurar seu navegador para recusar cookies. Nesse caso, a Site poderá não operar corretamente todas as suas funcionalidades, ou ocasionar lentidão para carregar os conteúdos.</p>
                <p>Por sua vez, os beacons (também conhecidos como pixel tags ou clear gifs) servem para ajudar a gerenciar e aperfeiçoar nossos serviços, sistemas, publicidade e anúncios online e demais ferramentas. Beacons possibilitam o reconhecimento de um cookie de um navegador quando este visita o site no qual o beacon está localizado, e a registrar qual publicidade de banner leva o Usuário a determinado site.</p>
                <h3>5. OBJETIVO DAS INFORMAÇÕES COLETADAS</h3>
                <p>As informações coletadas pela Site são armazenadas com o objetivo de: (i) caracterizar as suas preferências pessoais para aprimorar e customizar a sua experiência no uso da Site; (ii) contatá-lo diretamente para comunicar sobre alterações das ferramentas e novas funcionalidades da Site; (iii) analisar, elaborar e gerenciar suas Propostas para Captação de Recursos e as correspondentes Propostas de Crédito; (iv) gerenciar aplicações, recomendar investimentos e fazer cobranças; e (v) classificar e agrupar informações de Usuários, assim como consolidar dados estatísticos a respeito desses, inclusive para definir a composição da base de Usuários da Site e o volume de tráfego em nossos servidores.</p>
                <p>O uso das informações coletadas e/ou armazenadas exige o processamento de dados que poderá ser feito pela própria AllCred Promotora ou por parceiros contratados para esse fim, no Brasil ou no exterior, que também estarão sujeitos a esta Política de Privacidade. Você expressamente concorda com a transferência desses dados a outros agentes de mercado, tais como instituições financeiras, que serão necessárias na intermediação e demais atividades relacionadas às transações realizadas na Site. A AllCred Promotora emprega sistemas de segurança usualmente adotados pelo mercado para proteger suas informações contra acessos desautorizados, mas não garante que alguma informação pessoal não será acessada por terceiros não autorizados.</p>
                <p>Exceto conforme o previsto nesta Política de Privacidade e nos Termos de Uso AllCred Promotora, a AllCred Promotora não divulga a quaisquer terceiros as informações pessoais identificáveis fornecidas por Você. No entanto, caso seja solicitada por uma ordem expedida por autoridade competente no cumprimento de suas atribuições legais (tanto no Brasil como no exterior), ou em caso de violações ou suspeita de violações desta Política de Privacidade, dos Termos de Uso AllCred Promotora ou da lei aplicável, poderá ser requerido à AllCred Promotora disponibilizar as informações pessoais que estiverem armazenadas. A AllCred Promotora, porém, se compromete a revelar as informações limitando-se ao mínimo necessário para atingir as finalidades exigidas. As suas informações pessoais também poderão ser transferidas no caso de fusão, aquisição ou venda de ativos da AllCred Promotora. Caso o processamento das informações após estes eventos seja alterado, a AllCred Promotora notificará Você por meio do e-mail informado por Você em seu cadastro.</p>
                <h3>6. DEPOIMENTOS</h3>
                <p>A AllCred Promotora armazena e poderá realizar possíveis publicações dos depoimentos satisfeitos pelo Usuário no site, podendo conter dentro destes os nomes pessoais. Caso o Usuário deseje atualizar ou remover os seus depoimentos, este poderá entrar em contato com a AllCred Promotora por email: sac@allcredpromotora.com.br.</p>
                <h3>7. ALTERAÇÕES DA POLÍTICA DE PRIVACIDADE</h3>
                <p>A presente Política de Privacidade poderá ser alterada a qualquer tempo, dispensada a sua notificação prévia, sendo sua responsabilidade visitar essa página sempre que utilizar a Site para permanecer informado a respeito do tratamento que é conferido aos seus dados pessoais e da política de privacidade como um todo. Sem prejuízo do disposto, caso as alterações sejam significativas, colocaremos um aviso com mais destaque em nosso website, ou lhe enviaremos um e-mail. A sua contínua utilização da Site significa sua aderência e concordância com a atual versão dessa Política de Privacidade.</p>
                <h3>8. SITES DE TERCEIROS</h3>
                <p>A Site PODERÁ FORNECER LINKS PARA OUTROS SITES DA INTERNET OU OUTROS RECURSOS. ESTES LINKS SERÃO DISPONIBILIZADOS COMO UMA CONVENIÊNCIA AOS USUÁRIOS E, COMO A ALLCRED PROMOTORA NÃO TEM CONTROLE SOBRE TAIS SITES OU RECURSOS EXTERNOS, O USUÁRIO RECONHECE E CONCORDA QUE A ALLCRED PROMOTORA NÃO É RESPONSÁVEL E NÃO ENDOSSA OU SE RESPONSABILIZA POR QUALQUER CONTEÚDO, PROPAGANDA, PRODUTOS, SERVIÇOS, ASSIM COMO PELOS TERMOS DE USO E POLÍTICAS DE PRIVACIDADE DESSES WEBSITES OU OUTROS MATERIAIS CONTIDOS OU DISPONIBILIZADOS POR INTERMÉDIO DESSES. O USUÁRIO DEVE SE INFORME SOBRE OS TERMOS DE USO,POLÍTICAS DE PRIVACIDADE E DEMAIS DOCUMENTOS QUE POSSAM REGER SEU ACESSO OU UTILIZAÇÃO DE SITES DE TERCEIROS ANTES DE FORNECER QUALQUER TIPO DE INFORMAÇÃO OU ACESSAR OU UTILIZAR QUALQUER RECURSO NESSES AMBIENTES.</p>
                <p>Sites, conteúdos e aplicativos de terceiros (incluindo, sem limitação, outros Usuários), assim como afiliados, subcontratados ou parceiros comerciais da AllCred Promotora poderão utilizar seus próprios cookies ou beacons, os quais podem não operar nos mesmos termos desta Política de Privacidade. Dessa forma, a AllCred Promotora não se responsabiliza por estes sites e conteúdos e, ainda, não compartilha, subscreve, monitora, valida ou aceita a forma como esses sites ou ferramentas de armazenamento de conteúdo coletam, processam e transferem suas informações pessoais. Você deve consultar as respectivas políticas de privacidade de tais sites para se informar adequadamente a respeito do uso de suas informações pessoais por outros sites ou outras ferramentas.</p>
                <p>O Usuário expressamente reconhece e concorda que a AllCred Promotora não será responsável, direta ou indiretamente, por quaisquer perdas e danos que sejam efetivas ou alegadamente causados por, ou em conexão, pela confiança depositada nas informações, bens e serviços disponíveis no ou através de tais sites de terceiros.</p>
                <h3>9. SUPORTE</h3>
                <p>Em caso de maiores esclarecimentos ou quaisquer dúvidas sobre a Política de Privacidade, a AllCred Promotora está disponível para atendê-lo por meio de e-mail sac@allcredpromotora.com.br.</p>
                <h3>10. RESPONSABILIDADE DOS USUÁRIOS</h3>
                <p>Os Usuários se responsabilizam civil e criminalmente pela veracidade dos dados fornecidos na Site, bem como se comprometem a atualizar seus dados sempre que houver qualquer alteração.</p>
                <h3>11. GERAL</h3>
                <p>A proibição, invalidade ou inexequibilidade de qualquer disposição desta Política de Privacidade não invalidará ou afetará a mesma como um todo, devendo permanecer em vigor todas as demais disposições deste instrumento que não tenham sido afetadas pela proibição, invalidade ou inexequibilidade da cláusula inoperante.</p>
			</article>
			<!-- End Main Content -->
		</div>
	</div>
</div>
<?php include("../_footer.php") ?>